version: '3.8'

networks:
  default:
    driver: bridge
    external: false

services:
  equipment-zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: equipment-zookeeper
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  equipment-kafka:
    image: bitnami/kafka:3.1.0
    container_name: equipment-kafka
    restart: on-failure
    volumes:
      - ./kafka:/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=equipment-zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://equipment-kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - equipment-zookeeper
    # ports:
    #   - 9092:9092

  equipment-mongodb:
    image: mongo:5
    container_name: equipment-mongodb
    restart: on-failure
    volumes:
      - ./mongodb/config:/data/configdb
      - ./mongodb/data:/data/db
    # ports:
    #   - 27017:27017

  equipment-back:
    build: ./equipment-back/
    image: ablocker/equipment-back:latest
    container_name: equipment-back
    restart: on-failure
    depends_on:
      - equipment-mongodb
    # ports:
    #   - 8081:8081
  
  equipment-sensor:
    build: ./equipment-sensor/
    image: ablocker/equipment-sensor:latest
    container_name: equipment-sensor
    restart: on-failure
    depends_on:
      - equipment-kafka
    ports:
      - 8083:8083
  
  equipment-image:
    build: ./equipment-image/
    image: ablocker/equipment-image:latest
    container_name: equipment-image
    restart: on-failure
    volumes:
      - ./equipment-image/public:/equipment-image/public
    # ports:
    #   - 8082:8082
  
  equipment-front:
    build: ./equipment-front/
    image: ablocker/equipment-front:latest
    container_name: equipment-front
    restart: on-failure
    ports:
      # - 80:80
      - 8080:443
    depends_on:
      - equipment-back
      - equipment-image
      - equipment-sensor
  
  # equipment-nginx:
  #   image: nginx:stable-alpine
  #   container_name: equipment-nginx
  #   restart: on-failure
  #   volumes:
  #     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - equipment-back
  #     - equipment-image
  #     - equipment-front
