version: '3.8'

networks:
  default:
    driver: bridge
    external: false

services:
  equipment-mongodb:
    image: mongo:5
    container_name: equipment-mongodb
    restart: on-failure
    volumes:
      - ./mongodb/config:/data/configdb
      - ./mongodb/data:/data/db
    # ports:
    #   - 27017:27017

  equipment-back:
    build: ./equipment-back/
    image: ablocker/equipment-back:latest
    container_name: equipment-back
    restart: on-failure
    depends_on:
      - equipment-mongodb
    # ports:
    #   - 8081:8081
  
  equipment-sensor:
    build: ./equipment-sensor/
    image: ablocker/equipment-sensor:latest
    container_name: equipment-sensor
    restart: on-failure
    ports:
      - 8083:8083
  
  equipment-image:
    build: ./equipment-image/
    image: ablocker/equipment-image:latest
    container_name: equipment-image
    restart: on-failure
    volumes:
      - ./equipment-image/public:/equipment-image/public
    # ports:
    #   - 8082:8082
  
  equipment-front:
    build: ./equipment-front/
    image: ablocker/equipment-front:latest
    container_name: equipment-front
    restart: on-failure
    ports:
      # - 80:80
      - 8080:443
    depends_on:
      - equipment-back
      - equipment-image
  
  # equipment-nginx:
  #   image: nginx:stable-alpine
  #   container_name: equipment-nginx
  #   restart: on-failure
  #   volumes:
  #     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - equipment-back
  #     - equipment-image
  #     - equipment-front
